name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PARALLEL_WORKERS: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SQLite
        run: sudo apt-get install -y libsqlite3-dev
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set execute permissions for bin/rake
        run: chmod +x bin/rake
      - name: Set execute permissions for bin/rails
        run: chmod +x bin/rails
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate binstubs for bundler-audit
        run: bundle binstubs bundler-audit
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Generate binstubs for brakeman
        run: bundle binstubs brakeman
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
